import { vi, describe, it, expect, beforeEach, afterEach } from "vitest";
import { createClient, type Client } from "@libsql/client";
import fs from "fs";
import path from "path";
import type { WishlistItem } from "@/types/wishlist";

// ---------------------------------------------------------------------------
// Module-level mock state - declared outside describe blocks
// ---------------------------------------------------------------------------

let testClient: Client;

const mockCookiesGet = vi.fn();
const mockCookiesSet = vi.fn();
const mockCookiesDelete = vi.fn();
const mockGetCurrentSessionId = vi.fn();
const mockInitSessionDb = vi.fn();

// ---------------------------------------------------------------------------
// Mock: @/lib/session-db (in-memory SQLite)
// ---------------------------------------------------------------------------

vi.mock("@/lib/session-db", () => ({
  initSessionDb: (...args: unknown[]) => mockInitSessionDb(...args),
}));

// ---------------------------------------------------------------------------
// Mock: @/lib/session
// ---------------------------------------------------------------------------

vi.mock("@/lib/session", () => ({
  getCurrentSessionId: (...args: unknown[]) => mockGetCurrentSessionId(...args),
}));

// ---------------------------------------------------------------------------
// Mock: next/headers
// ---------------------------------------------------------------------------

vi.mock("next/headers", () => ({
  cookies: vi.fn(() => ({
    get: mockCookiesGet,
    set: mockCookiesSet,
    delete: mockCookiesDelete,
  })),
}));

// ---------------------------------------------------------------------------
// Import module under test AFTER all mocks are declared
// ---------------------------------------------------------------------------

const { getWishlist, addToWishlist, removeFromWishlist } = await import("@/lib/wishlist");

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

function makeWishlistItem(overrides: Partial<WishlistItem> = {}): WishlistItem {
  const id = Math.random().toString(36).slice(2, 10);
  return {
    skinUuid: `skin-uuid-${id}`,
    displayName: `Test Skin ${id}`,
    displayIcon: `https://example.com/icon-${id}.png`,
    tierColor: "#FFFFFF",
    addedAt: new Date().toISOString(),
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// beforeEach: fresh in-memory SQLite + mock reset
// ---------------------------------------------------------------------------

beforeEach(async () => {
  // Create fresh in-memory SQLite per test
  testClient = createClient({ url: ":memory:" });
  await testClient.execute(
    "CREATE TABLE IF NOT EXISTS wishlists (puuid TEXT NOT NULL PRIMARY KEY, skins TEXT NOT NULL)",
  );

  // CRITICAL: Use mockReset() NOT mockClear() to reset implementation
  mockCookiesGet.mockReset();
  mockCookiesSet.mockReset();
  mockCookiesDelete.mockReset();
  mockGetCurrentSessionId.mockReset();
  mockInitSessionDb.mockReset();

  // Default resolved values
  mockGetCurrentSessionId.mockResolvedValue("test-session-id");
  mockInitSessionDb.mockResolvedValue(testClient);
  mockCookiesGet.mockReturnValue(undefined);
});

// ---------------------------------------------------------------------------
// Tests: readWishlistItems() via getWishlist()
// ---------------------------------------------------------------------------

describe("readWishlistItems() - SQLite read path", () => {
  it("returns items from SQLite when available", async () => {
    const items = [makeWishlistItem(), makeWishlistItem()];
    const puuid = "test-puuid-123";

    // Mock SQLite returning rows
    await testClient.execute({
      sql: "INSERT INTO wishlists (puuid, skins) VALUES (?, ?)",
      args: [puuid, JSON.stringify(items)],
    });

    const result = await getWishlist(puuid);

    expect(result.items).toHaveLength(2);
    expect(result.count).toBe(2);
    expect(mockCookiesGet).not.toHaveBeenCalled();
  });

  it("keeps items after the session id is rotated (login / account switch)", async () => {
    const items = [makeWishlistItem()];
    const puuid = "test-puuid-rotate";

    await testClient.execute({
      sql: "INSERT INTO wishlists (puuid, skins) VALUES (?, ?)",
      args: [puuid, JSON.stringify(items)],
    });

    // Session id regenerated by a new login / addAccount / switchAccount
    mockGetCurrentSessionId.mockResolvedValue("rotated-session-id");

    const result = await getWishlist(puuid);

    expect(result.items).toHaveLength(1);
    expect(result.items[0]!.skinUuid).toBe(items[0]!.skinUuid);
  });

  it("returns empty array when sessionId is null", async () => {
    mockGetCurrentSessionId.mockResolvedValue(null);
    const puuid = "test-puuid-123";

    const result = await getWishlist(puuid);

    expect(result.items).toHaveLength(0);
    expect(result.count).toBe(0);
  });

  it("returns empty array when SQLite returns no rows and no cookie exists", async () => {
    // SQLite returns empty (testClient is fresh in-memory with no data)
    mockCookiesGet.mockReturnValue(undefined);
    const puuid = "test-puuid-123";

    const result = await getWishlist(puuid);

    expect(result.items).toHaveLength(0);
    expect(result.count).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// Tests: readWishlistItems() - cookie fallback and migration
// ---------------------------------------------------------------------------

describe("readWishlistItems() - cookie fallback and migration", () => {
  it("falls back to cookie when SQLite returns empty", async () => {
    const items = [makeWishlistItem(), makeWishlistItem()];
    const puuid = "test-puuid-456";
    const _cookieName = `valorant_wishlist_${puuid.substring(0, 8)}`;

    // SQLite returns empty (fresh in-memory)
    mockCookiesGet.mockReturnValue({ value: JSON.stringify(items) });

    const result = await getWishlist(puuid);

    expect(result.items).toHaveLength(2);
    expect(result.count).toBe(2);
    // Verify items were migrated to SQLite
    const sqliteResult = await testClient.execute({
      sql: "SELECT skins FROM wishlists WHERE puuid = ?",
      args: [puuid],
    });
    expect(sqliteResult.rows.length).toBe(1);
  });

  it("returns empty array when both SQLite and cookie fail", async () => {
    // SQLite returns empty (fresh in-memory)
    mockCookiesGet.mockReturnValue(undefined);
    const puuid = "test-puuid-789";

    const result = await getWishlist(puuid);

    expect(result.items).toHaveLength(0);
    expect(result.count).toBe(0);
  });

  it("migrates cookie to SQLite atomically and deletes cookie after successful write", async () => {
    const items = [makeWishlistItem()];
    const puuid = "test-puuid-migrate";
    const cookieName = `valorant_wishlist_${puuid.substring(0, 8)}`;

    mockCookiesGet.mockReturnValue({ value: JSON.stringify(items) });

    await getWishlist(puuid);

    // Verify SQLite INSERT was called (migration happened)
    const sqliteResult = await testClient.execute({
      sql: "SELECT skins FROM wishlists WHERE puuid = ?",
      args: [puuid],
    });
    expect(sqliteResult.rows.length).toBe(1);

    // Verify cookie was deleted ONLY after successful migration
    expect(mockCookiesDelete).toHaveBeenCalledWith(cookieName);
  });

  it("does not delete cookie if SQLite write fails during migration", async () => {
    // Set up a mock that makes SQLite write fail
    mockInitSessionDb.mockResolvedValue({
      execute: vi.fn().mockRejectedValue(new Error("SQLite write error")),
    } as unknown as Client);

    const items = [makeWishlistItem()];
    const puuid = "test-puuid-fail";

    mockCookiesGet.mockReturnValue({ value: JSON.stringify(items) });

    // Should still return items (fail-silent UX) but cookie should NOT be deleted
    const result = await getWishlist(puuid);

    // Error is caught internally, returns empty array
    expect(result.items).toHaveLength(0);
    expect(mockCookiesDelete).not.toHaveBeenCalled();
  });
});

// ---------------------------------------------------------------------------
// Tests: addToWishlist() uses readWishlistItems()
// ---------------------------------------------------------------------------

describe("addToWishlist()", () => {
  it("adds item to wishlist retrieved via readWishlistItems()", async () => {
    const puuid = "test-puuid-add";
    const existingItems = [makeWishlistItem()];
    const newItem = makeWishlistItem({ skinUuid: "new-skin-uuid" });

    // Pre-populate SQLite
    await testClient.execute({
      sql: "INSERT INTO wishlists (puuid, skins) VALUES (?, ?)",
      args: [puuid, JSON.stringify(existingItems)],
    });

    const result = await addToWishlist(puuid, newItem);

    expect(result.items[0]).toMatchObject({ skinUuid: newItem.skinUuid });
    expect(result.count).toBe(2);
  });

  it("does not duplicate when item already exists", async () => {
    const puuid = "test-puuid-dup";
    const existingItem = makeWishlistItem({ skinUuid: "duplicate-skin" });

    // Pre-populate SQLite
    await testClient.execute({
      sql: "INSERT INTO wishlists (puuid, skins) VALUES (?, ?)",
      args: [puuid, JSON.stringify([existingItem])],
    });

    const result = await addToWishlist(puuid, existingItem);

    // Should still return 1 item (not duplicated)
    expect(result.items).toHaveLength(1);
    expect(result.count).toBe(1);
  });

  it("handles adding to empty wishlist", async () => {
    const puuid = "test-puuid-empty";
    const newItem = makeWishlistItem();

    const result = await addToWishlist(puuid, newItem);

    expect(result.items).toHaveLength(1);
    expect(result.count).toBe(1);
    expect(result.items[0]!.skinUuid).toBe(newItem.skinUuid);
  });

  it("writes nothing when there is no session (auth guard)", async () => {
    mockGetCurrentSessionId.mockResolvedValue(null);
    const puuid = "test-puuid-unauthenticated-add";

    const result = await addToWishlist(puuid, makeWishlistItem());

    expect(result).toEqual({ items: [], count: 0 });
    // The session id is no longer part of the key, so only this guard keeps
    // an unauthenticated caller from writing the puuid-keyed row.
    const stored = await testClient.execute({
      sql: "SELECT skins FROM wishlists WHERE puuid = ?",
      args: [puuid],
    });
    expect(stored.rows).toHaveLength(0);
  });
});

// ---------------------------------------------------------------------------
// Tests: removeFromWishlist() uses readWishlistItems()
// ---------------------------------------------------------------------------

describe("removeFromWishlist()", () => {
  it("removes item from wishlist retrieved via readWishlistItems()", async () => {
    const puuid = "test-puuid-remove";
    const items = [
      makeWishlistItem({ skinUuid: "remove-me" }),
      makeWishlistItem({ skinUuid: "keep-me" }),
    ];

    // Pre-populate SQLite
    await testClient.execute({
      sql: "INSERT INTO wishlists (puuid, skins) VALUES (?, ?)",
      args: [puuid, JSON.stringify(items)],
    });

    const result = await removeFromWishlist(puuid, "remove-me");

    expect(result.items).toHaveLength(1);
    expect(result.items[0]!.skinUuid).toBe("keep-me");
    expect(result.count).toBe(1);
  });

  it("handles removing from empty wishlist gracefully", async () => {
    const puuid = "test-puuid-remove-empty";

    const result = await removeFromWishlist(puuid, "non-existent-skin");

    expect(result.items).toHaveLength(0);
    expect(result.count).toBe(0);
  });

  it("handles removing non-existent item gracefully", async () => {
    const puuid = "test-puuid-remove-none";
    const items = [makeWishlistItem({ skinUuid: "keep-skin" })];

    // Pre-populate SQLite
    await testClient.execute({
      sql: "INSERT INTO wishlists (puuid, skins) VALUES (?, ?)",
      args: [puuid, JSON.stringify(items)],
    });

    const result = await removeFromWishlist(puuid, "non-existent-skin");

    // Should return the unchanged wishlist (1 item)
    expect(result.items).toHaveLength(1);
    expect(result.count).toBe(1);
  });

  it("leaves the stored row alone when there is no session (auth guard)", async () => {
    const puuid = "test-puuid-unauthenticated-remove";
    const items = [makeWishlistItem({ skinUuid: "keep-skin" })];

    await testClient.execute({
      sql: "INSERT INTO wishlists (puuid, skins) VALUES (?, ?)",
      args: [puuid, JSON.stringify(items)],
    });

    mockGetCurrentSessionId.mockResolvedValue(null);

    const result = await removeFromWishlist(puuid, "keep-skin");

    expect(result).toEqual({ items: [], count: 0 });
    // Without the guard the empty read would be written back over the row,
    // wiping the account's favourites.
    const stored = await testClient.execute({
      sql: "SELECT skins FROM wishlists WHERE puuid = ?",
      args: [puuid],
    });
    expect(JSON.parse(stored.rows[0]!.skins as string)).toHaveLength(1);
  });
});

// ---------------------------------------------------------------------------
// Tests: error handling
// ---------------------------------------------------------------------------

describe("error handling", () => {
  it("handles getCurrentSessionId throwing gracefully", async () => {
    mockGetCurrentSessionId.mockRejectedValue(new Error("Session error"));
    const puuid = "test-puuid-session-error";

    const result = await getWishlist(puuid);

    expect(result.items).toHaveLength(0);
    expect(result.count).toBe(0);
  });

  it("handles initSessionDb throwing gracefully", async () => {
    mockInitSessionDb.mockRejectedValue(new Error("DB init error"));
    const puuid = "test-puuid-db-error";

    const result = await getWishlist(puuid);

    expect(result.items).toHaveLength(0);
    expect(result.count).toBe(0);
  });

  it("handles JSON parse error in cookie gracefully", async () => {
    const puuid = "test-puuid-parse-error";
    const _cookieName = `valorant_wishlist_${puuid.substring(0, 8)}`;

    // SQLite returns empty (fresh in-memory)
    mockCookiesGet.mockReturnValue({ value: "invalid-json" });

    const result = await getWishlist(puuid);

    // Error is caught, returns empty array
    expect(result.items).toHaveLength(0);
    expect(result.count).toBe(0);
  });
});

// ---------------------------------------------------------------------------
// Tests: concurrent writes (F19 — lost update)
// ---------------------------------------------------------------------------

describe("concurrent writes", () => {
  async function storedSkinUuids(puuid: string): Promise<string[]> {
    const stored = await testClient.execute({
      sql: "SELECT skins FROM wishlists WHERE puuid = ?",
      args: [puuid],
    });
    if (stored.rows.length === 0) return [];
    return (JSON.parse(stored.rows[0]!.skins as string) as WishlistItem[]).map(
      (item) => item.skinUuid,
    );
  }

  it("keeps both items when two additions overlap", async () => {
    const puuid = "test-puuid-concurrent-add";

    await Promise.all([
      addToWishlist(puuid, makeWishlistItem({ skinUuid: "skin-a" })),
      addToWishlist(puuid, makeWishlistItem({ skinUuid: "skin-b" })),
    ]);

    expect((await storedSkinUuids(puuid)).sort()).toEqual(["skin-a", "skin-b"]);
  });

  it("drops both items when two removals overlap", async () => {
    const puuid = "test-puuid-concurrent-remove";
    await testClient.execute({
      sql: "INSERT INTO wishlists (puuid, skins) VALUES (?, ?)",
      args: [
        puuid,
        JSON.stringify([
          makeWishlistItem({ skinUuid: "skin-a" }),
          makeWishlistItem({ skinUuid: "skin-b" }),
          makeWishlistItem({ skinUuid: "skin-keep" }),
        ]),
      ],
    });

    await Promise.all([
      removeFromWishlist(puuid, "skin-a"),
      removeFromWishlist(puuid, "skin-b"),
    ]);

    expect(await storedSkinUuids(puuid)).toEqual(["skin-keep"]);
  });

  it("applies both when an addition overlaps a removal", async () => {
    const puuid = "test-puuid-concurrent-mixed";
    await testClient.execute({
      sql: "INSERT INTO wishlists (puuid, skins) VALUES (?, ?)",
      args: [puuid, JSON.stringify([makeWishlistItem({ skinUuid: "skin-old" })])],
    });

    await Promise.all([
      addToWishlist(puuid, makeWishlistItem({ skinUuid: "skin-new" })),
      removeFromWishlist(puuid, "skin-old"),
    ]);

    expect(await storedSkinUuids(puuid)).toEqual(["skin-new"]);
  });
});

// ---------------------------------------------------------------------------
// Tests: concurrent writes against a real SQLite file (F19 — no lock failure)
// ---------------------------------------------------------------------------

describe("concurrent writes on a local SQLite file", () => {
  const dbPath = path.join(
    process.cwd(),
    ".session-data",
    `test-wishlist-concurrency-${Date.now()}.db`,
  );
  let fileClient: Client;

  beforeEach(async () => {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- test-owned path under .session-data; not user input
    fs.mkdirSync(path.dirname(dbPath), { recursive: true });
    fileClient = createClient({ url: "file:" + dbPath.replace(/\\/g, "/") });
    await fileClient.execute(
      "CREATE TABLE IF NOT EXISTS wishlists (puuid TEXT NOT NULL PRIMARY KEY, skins TEXT NOT NULL)",
    );
    mockInitSessionDb.mockResolvedValue(fileClient);
  });

  afterEach(() => {
    fileClient.close();
    fs.rmSync(dbPath, { force: true });
  });

  it("persists overlapping additions without a SQLITE_BUSY lock failure", async () => {
    const puuid = "test-puuid-file-concurrent";

    // Rejects (not just a wrong result) if the write path ever contended on
    // the file lock — the failure mode of an interactive write transaction.
    await Promise.all([
      addToWishlist(puuid, makeWishlistItem({ skinUuid: "skin-a" })),
      addToWishlist(puuid, makeWishlistItem({ skinUuid: "skin-b" })),
      addToWishlist(puuid, makeWishlistItem({ skinUuid: "skin-c" })),
    ]);

    const stored = await fileClient.execute({
      sql: "SELECT skins FROM wishlists WHERE puuid = ?",
      args: [puuid],
    });
    const skinUuids = (
      JSON.parse(stored.rows[0]!.skins as string) as WishlistItem[]
    ).map((item) => item.skinUuid);

    expect(skinUuids.sort()).toEqual(["skin-a", "skin-b", "skin-c"]);
  });
});

// ---------------------------------------------------------------------------
// Tests: concurrent writes while the legacy cookie is still being migrated
// ---------------------------------------------------------------------------

describe("concurrent writes during the legacy cookie migration", () => {
  it("keeps an overlapping add when the other request seeds SQLite from the cookie", async () => {
    const puuid = "test-puuid-cookie-migration-race";
    mockCookiesGet.mockReturnValue({
      value: JSON.stringify([makeWishlistItem({ skinUuid: "skin-old" })]),
    });

    // Both requests miss SQLite and fall back to the cookie. Delay the second
    // seed so it lands AFTER the first request already stored its item: the
    // seed must not overwrite what the first request wrote.
    let seeds = 0;
    const realExecute = testClient.execute.bind(testClient);
    const slowClient = {
      execute: async (stmt: unknown) => {
        const sql =
          typeof stmt === "string" ? stmt : (stmt as { sql: string }).sql;
        // The seed is the only statement binding the whole list as one param.
        if (sql.includes("INSERT INTO wishlists") && sql.includes("VALUES (?, ?)")) {
          seeds += 1;
          if (seeds === 2) await new Promise((resolve) => setTimeout(resolve, 20));
        }
        return realExecute(stmt as never);
      },
    } as unknown as Client;
    mockInitSessionDb.mockResolvedValue(slowClient);

    await Promise.all([
      addToWishlist(puuid, makeWishlistItem({ skinUuid: "skin-a" })),
      addToWishlist(puuid, makeWishlistItem({ skinUuid: "skin-b" })),
    ]);

    const stored = await testClient.execute({
      sql: "SELECT skins FROM wishlists WHERE puuid = ?",
      args: [puuid],
    });
    const skinUuids = (
      JSON.parse(stored.rows[0]!.skins as string) as WishlistItem[]
    ).map((item) => item.skinUuid);

    expect(skinUuids.sort()).toEqual(["skin-a", "skin-b", "skin-old"]);
  });
});
